#!/usr/bin/expect -f

set timeout -1
set CODE [lindex $argv 0];
spawn expressvpn activate
match_max 100000
expect {
	"Already activated. Logout from your account (y/N)?" {
		send "N\r"
	}
	"Enter activation code:" {
		send "$CODE\r"
		exp_continue
	}
	"Help improve ExpressVPN: Share crash reports, speed tests, usability diagnostics, and whether VPN connection attempts succeed. These reports never contain personally identifiable information. (Y/n)" {
		send "n\r"
	}
}
expect eof